### ISSUE TITLE
建议，请求，使用反馈。Suggestions, requests, use feedback

### ISSUE THREAD

**Issue by xiaohang4m9** [liulongbin1314/escook-theme#2]
空格、缩进过小，还请调整谢谢。
Space, indent too small, please adjust thank you

**Comment by xiaohang4m9** [comment]
@teacher-liu

**Comment by liulongbin1314** [comment]
用户可以直接在vscode的配置页面中自行调整缩进和空格的大小。主题只负责编辑器的外观颜色。
